### ISSUE TITLE
Cloning causes issue

### ISSUE THREAD

**Issue by digiajay** [NIVeriStandAdd-Ons/Jenkins-Autobuild#4]
When I clone this Git using my desktop, it clones in a folder named Jenkins-Autobuild.  I think if you rename this project to Autobuild, it would be able to clone directly to Autobuild where you have some hard-coded links in batch files.  Right now I have to download it as zip and unzip in the C:\Autobuild\ location.

**Comment by AndreasStark** [comment]
You can use the <directory> option to clone into a folder you'd like. Thanks for bringing this up, I updated the readme in commit 1f1a2c3 to prevent others from finding it out the hard way.
